# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5e59d1640731a5a170f264496e5724d9"
name = "VOPI "
application_url = "https://api.vopi.24rabbit.com"
embedded = false

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "https://api.vopi.24rabbit.com/api/v1/webhooks/shopify"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://api.vopi.24rabbit.com/api/v1/oauth/shopify/callback"
]
